services:
  sqlserver:
    # public preview build with native VECTOR support
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'StrongPassw0rd'
      MSSQL_PID: 'Developer'
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./scripts/init-database.sql:/scripts/init-database.sql:ro
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr &  
        echo '⏳ Waiting for SQL Server to start…';              
        until /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'StrongPassw0rd' -C -Q 'SELECT 1;' > /dev/null 2>&1; do
          sleep 1;
        done;
        echo '✅ SQL Server is up — creating VectorStore DB if needed…';
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'StrongPassw0rd' -C -Q \"IF DB_ID('VectorStore') IS NULL CREATE DATABASE [VectorStore];\";
        echo '🚀 Init complete, handing control back to sqlservr';
        wait
      "
volumes:
  sqlserver-data:
    driver: local
